# Generated by Django 4.1.6 on 2023-05-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
