# Generated by Django 4.1.6 on 2023-05-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitapturu',
            name='sinif',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='dersturu',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='kitapturu',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='sinif',
        ),
        migrations.DeleteModel(
            name='DersTuru',
        ),
        migrations.DeleteModel(
            name='KitapTuru',
        ),
    ]
