# Generated by Django 4.1.6 on 2023-05-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_remove_kitapturu_sinif_remove_kitap_dersturu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='sinif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.sinif'),
        ),
        migrations.CreateModel(
            name='KitapTuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.sinif')),
            ],
        ),
        migrations.CreateModel(
            name='DersTuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('kitapturu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.kitapturu')),
            ],
        ),
        migrations.AddField(
            model_name='kitap',
            name='dersturu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.dersturu'),
        ),
        migrations.AddField(
            model_name='kitap',
            name='kitapturu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.kitapturu'),
        ),
    ]
