# Generated by Django 4.1.6 on 2023-05-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_kitap_sinif_kitapturu_dersturu_kitap_dersturu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitap',
            name='dersturu',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='kitapturu',
        ),
        migrations.DeleteModel(
            name='DersTuru',
        ),
    ]
