# Generated by Django 4.1.6 on 2023-05-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_kitap_kitapturu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersTuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('kitapturu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.kitapturu')),
            ],
        ),
        migrations.AddField(
            model_name='kitap',
            name='dersturu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.dersturu'),
        ),
    ]
