# Generated by Django 4.1.6 on 2023-05-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_dersturu_kitap_dersturu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitapismi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('kitapismi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.dersturu')),
            ],
        ),
        migrations.AddField(
            model_name='kitap',
            name='kitapismi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.kitapismi'),
        ),
    ]
